/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSubscriptionsRouteImport } from './routes/_authenticated/subscriptions'
import { Route as AuthenticatedSocialRouteImport } from './routes/_authenticated/social'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedOutreachRouteImport } from './routes/_authenticated/outreach'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedIssuesRouteImport } from './routes/_authenticated/issues'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings.users'
import { Route as AuthenticatedSettingsTenantsRouteImport } from './routes/_authenticated/settings.tenants'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings.profile'
import { Route as AuthenticatedSettingsPlansRouteImport } from './routes/_authenticated/settings.plans'
import { Route as AuthenticatedSettingsMilestonesRouteImport } from './routes/_authenticated/settings.milestones'
import { Route as AuthenticatedSettingsLeadsRouteImport } from './routes/_authenticated/settings.leads'
import { Route as AuthenticatedSettingsFiscalYearRouteImport } from './routes/_authenticated/settings.fiscal-year'
import { Route as AuthenticatedSettingsFieldsRouteImport } from './routes/_authenticated/settings.fields'
import { Route as AuthenticatedSettingsCostProposalRouteImport } from './routes/_authenticated/settings.cost-proposal'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSubscriptionsRoute =
  AuthenticatedSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSocialRoute = AuthenticatedSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOutreachRoute = AuthenticatedOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIssuesRoute = AuthenticatedIssuesRouteImport.update({
  id: '/issues',
  path: '/issues',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTenantsRoute =
  AuthenticatedSettingsTenantsRouteImport.update({
    id: '/tenants',
    path: '/tenants',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPlansRoute =
  AuthenticatedSettingsPlansRouteImport.update({
    id: '/plans',
    path: '/plans',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsMilestonesRoute =
  AuthenticatedSettingsMilestonesRouteImport.update({
    id: '/milestones',
    path: '/milestones',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsLeadsRoute =
  AuthenticatedSettingsLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsFiscalYearRoute =
  AuthenticatedSettingsFiscalYearRouteImport.update({
    id: '/fiscal-year',
    path: '/fiscal-year',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsFieldsRoute =
  AuthenticatedSettingsFieldsRouteImport.update({
    id: '/fields',
    path: '/fields',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsCostProposalRoute =
  AuthenticatedSettingsCostProposalRouteImport.update({
    id: '/cost-proposal',
    path: '/cost-proposal',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/issues': typeof AuthenticatedIssuesRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/outreach': typeof AuthenticatedOutreachRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/social': typeof AuthenticatedSocialRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/settings/cost-proposal': typeof AuthenticatedSettingsCostProposalRoute
  '/settings/fields': typeof AuthenticatedSettingsFieldsRoute
  '/settings/fiscal-year': typeof AuthenticatedSettingsFiscalYearRoute
  '/settings/leads': typeof AuthenticatedSettingsLeadsRoute
  '/settings/milestones': typeof AuthenticatedSettingsMilestonesRoute
  '/settings/plans': typeof AuthenticatedSettingsPlansRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/tenants': typeof AuthenticatedSettingsTenantsRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/issues': typeof AuthenticatedIssuesRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/outreach': typeof AuthenticatedOutreachRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/social': typeof AuthenticatedSocialRoute
  '/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/settings/cost-proposal': typeof AuthenticatedSettingsCostProposalRoute
  '/settings/fields': typeof AuthenticatedSettingsFieldsRoute
  '/settings/fiscal-year': typeof AuthenticatedSettingsFiscalYearRoute
  '/settings/leads': typeof AuthenticatedSettingsLeadsRoute
  '/settings/milestones': typeof AuthenticatedSettingsMilestonesRoute
  '/settings/plans': typeof AuthenticatedSettingsPlansRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/tenants': typeof AuthenticatedSettingsTenantsRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/issues': typeof AuthenticatedIssuesRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/outreach': typeof AuthenticatedOutreachRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/social': typeof AuthenticatedSocialRoute
  '/_authenticated/subscriptions': typeof AuthenticatedSubscriptionsRoute
  '/_authenticated/settings/cost-proposal': typeof AuthenticatedSettingsCostProposalRoute
  '/_authenticated/settings/fields': typeof AuthenticatedSettingsFieldsRoute
  '/_authenticated/settings/fiscal-year': typeof AuthenticatedSettingsFiscalYearRoute
  '/_authenticated/settings/leads': typeof AuthenticatedSettingsLeadsRoute
  '/_authenticated/settings/milestones': typeof AuthenticatedSettingsMilestonesRoute
  '/_authenticated/settings/plans': typeof AuthenticatedSettingsPlansRoute
  '/_authenticated/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings/tenants': typeof AuthenticatedSettingsTenantsRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/calendar'
    | '/crm'
    | '/dashboard'
    | '/issues'
    | '/leads'
    | '/notifications'
    | '/outreach'
    | '/projects'
    | '/settings'
    | '/social'
    | '/subscriptions'
    | '/settings/cost-proposal'
    | '/settings/fields'
    | '/settings/fiscal-year'
    | '/settings/leads'
    | '/settings/milestones'
    | '/settings/plans'
    | '/settings/profile'
    | '/settings/tenants'
    | '/settings/users'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/calendar'
    | '/crm'
    | '/dashboard'
    | '/issues'
    | '/leads'
    | '/notifications'
    | '/outreach'
    | '/projects'
    | '/settings'
    | '/social'
    | '/subscriptions'
    | '/settings/cost-proposal'
    | '/settings/fields'
    | '/settings/fiscal-year'
    | '/settings/leads'
    | '/settings/milestones'
    | '/settings/plans'
    | '/settings/profile'
    | '/settings/tenants'
    | '/settings/users'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/_authenticated/calendar'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/issues'
    | '/_authenticated/leads'
    | '/_authenticated/notifications'
    | '/_authenticated/outreach'
    | '/_authenticated/projects'
    | '/_authenticated/settings'
    | '/_authenticated/social'
    | '/_authenticated/subscriptions'
    | '/_authenticated/settings/cost-proposal'
    | '/_authenticated/settings/fields'
    | '/_authenticated/settings/fiscal-year'
    | '/_authenticated/settings/leads'
    | '/_authenticated/settings/milestones'
    | '/_authenticated/settings/plans'
    | '/_authenticated/settings/profile'
    | '/_authenticated/settings/tenants'
    | '/_authenticated/settings/users'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/subscriptions': {
      id: '/_authenticated/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof AuthenticatedSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/social': {
      id: '/_authenticated/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof AuthenticatedSocialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/outreach': {
      id: '/_authenticated/outreach'
      path: '/outreach'
      fullPath: '/outreach'
      preLoaderRoute: typeof AuthenticatedOutreachRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/issues': {
      id: '/_authenticated/issues'
      path: '/issues'
      fullPath: '/issues'
      preLoaderRoute: typeof AuthenticatedIssuesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/tenants': {
      id: '/_authenticated/settings/tenants'
      path: '/tenants'
      fullPath: '/settings/tenants'
      preLoaderRoute: typeof AuthenticatedSettingsTenantsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/profile': {
      id: '/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/plans': {
      id: '/_authenticated/settings/plans'
      path: '/plans'
      fullPath: '/settings/plans'
      preLoaderRoute: typeof AuthenticatedSettingsPlansRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/milestones': {
      id: '/_authenticated/settings/milestones'
      path: '/milestones'
      fullPath: '/settings/milestones'
      preLoaderRoute: typeof AuthenticatedSettingsMilestonesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/leads': {
      id: '/_authenticated/settings/leads'
      path: '/leads'
      fullPath: '/settings/leads'
      preLoaderRoute: typeof AuthenticatedSettingsLeadsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/fiscal-year': {
      id: '/_authenticated/settings/fiscal-year'
      path: '/fiscal-year'
      fullPath: '/settings/fiscal-year'
      preLoaderRoute: typeof AuthenticatedSettingsFiscalYearRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/fields': {
      id: '/_authenticated/settings/fields'
      path: '/fields'
      fullPath: '/settings/fields'
      preLoaderRoute: typeof AuthenticatedSettingsFieldsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/cost-proposal': {
      id: '/_authenticated/settings/cost-proposal'
      path: '/cost-proposal'
      fullPath: '/settings/cost-proposal'
      preLoaderRoute: typeof AuthenticatedSettingsCostProposalRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsCostProposalRoute: typeof AuthenticatedSettingsCostProposalRoute
  AuthenticatedSettingsFieldsRoute: typeof AuthenticatedSettingsFieldsRoute
  AuthenticatedSettingsFiscalYearRoute: typeof AuthenticatedSettingsFiscalYearRoute
  AuthenticatedSettingsLeadsRoute: typeof AuthenticatedSettingsLeadsRoute
  AuthenticatedSettingsMilestonesRoute: typeof AuthenticatedSettingsMilestonesRoute
  AuthenticatedSettingsPlansRoute: typeof AuthenticatedSettingsPlansRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsTenantsRoute: typeof AuthenticatedSettingsTenantsRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsCostProposalRoute:
    AuthenticatedSettingsCostProposalRoute,
  AuthenticatedSettingsFieldsRoute: AuthenticatedSettingsFieldsRoute,
  AuthenticatedSettingsFiscalYearRoute: AuthenticatedSettingsFiscalYearRoute,
  AuthenticatedSettingsLeadsRoute: AuthenticatedSettingsLeadsRoute,
  AuthenticatedSettingsMilestonesRoute: AuthenticatedSettingsMilestonesRoute,
  AuthenticatedSettingsPlansRoute: AuthenticatedSettingsPlansRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsTenantsRoute: AuthenticatedSettingsTenantsRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIssuesRoute: typeof AuthenticatedIssuesRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOutreachRoute: typeof AuthenticatedOutreachRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedSocialRoute: typeof AuthenticatedSocialRoute
  AuthenticatedSubscriptionsRoute: typeof AuthenticatedSubscriptionsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIssuesRoute: AuthenticatedIssuesRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOutreachRoute: AuthenticatedOutreachRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedSocialRoute: AuthenticatedSocialRoute,
  AuthenticatedSubscriptionsRoute: AuthenticatedSubscriptionsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
